# Generated by Django 6.0.3 on 2026-03-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_about_photo_alter_personal_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.CharField(max_length=200)),
                ('fecha', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
