# Generated by Django 6.0.3 on 2026-03-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('fecha_inicio', models.CharField(max_length=50)),
                ('fecha_fin', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
